export type AreaSlug = "dallas" | "garland" | "mesquite" | "richardson" | "plano" | "sachse" | "rowlett" | "forney" | "rockwall" | "wylie"

export type AreaGuide = {
  slug: AreaSlug
  city: string
  countyContext: string
  overview: string
  searchFocus: string
  neighborhoods: string[]
  housing: string[]
  buyingTips: string[]
  affordability: string
  marketOverview: string
  schoolNote: string
  cityUrl: string
  faqs: Array<{ question: string; answer: string }>
}

const sharedFaq = (city: string) => [
  { question: `How should a first-time buyer prepare for a home search in ${city}?`, answer: "Start with a lender or approved program conversation, choose a sustainable monthly-cost target, identify the property condition you can manage, and rank location needs before touring." },
  { question: `How can I compare affordability in ${city}?`, answer: "Compare the complete monthly and upfront cost: principal, interest, taxes, insurance, mortgage insurance, association dues, utilities, maintenance, down payment, and closing costs. Use current written estimates rather than a citywide average." },
  { question: `Where can I verify schools for a ${city} address?`, answer: "School boundaries can cross city lines and change. Verify the exact address with the applicable district and the Texas Education Agency before making a housing decision." },
  { question: `Does this guide show live homes for sale in ${city}?`, answer: "No. This guide provides planning information. Live inventory must come from an approved MLS or IDX provider and should be verified at the time of the search." },
]

export const AREAS: Record<AreaSlug, AreaGuide> = {
  dallas: { slug: "dallas", city: "Dallas", countyContext: "Dallas County and the wider DFW region", overview: "Dallas offers a large, varied housing search where price, property age, taxes, commute patterns, and neighborhood-level condition can change substantially across the city.", searchFocus: "Break a Dallas search into manageable zones based on verified travel needs, home type, monthly cost, and condition rather than trying to compare the entire city at once.", neighborhoods: ["Oak Cliff", "East Dallas", "Lake Highlands", "Far North Dallas"], housing: ["Established single-family homes", "Townhomes and condominiums", "New infill construction", "Homes with varied renovation needs"], buyingTips: ["Verify the taxing jurisdictions for the exact address", "Review flood information and insurance early", "Compare renovation needs with available reserves", "Test important travel routes at realistic times"], affordability: "Dallas affordability is property-specific. Taxes, insurance, association dues, condition, and location can make similarly priced homes carry different monthly and long-term costs.", marketOverview: "Inventory, pricing, concessions, and competition change by property type and submarket. Use current MLS evidence and recent comparable activity supplied by qualified professionals before making an offer.", schoolNote: "Addresses may be served by Dallas ISD or another district depending on location. Verify attendance boundaries directly.", cityUrl: "https://dallascityhall.com/", faqs: sharedFaq("Dallas") },
  garland: { slug: "garland", city: "Garland", countyContext: "Dallas County and the eastern DFW region", overview: "Garland offers established North Texas housing, townhome options, and newer pockets within reach of major employment and service areas.", searchFocus: "Compare condition, taxes, transportation needs, program requirements, and the complete monthly cost before treating list price as affordability.", neighborhoods: ["Firewheel", "Duck Creek", "Club Hill", "Downtown Garland"], housing: ["One-story brick homes", "Ranch-style homes", "Townhomes", "Newer suburban construction"], buyingTips: ["Confirm the exact school attendance boundary", "Evaluate foundation, roof, drainage, and major systems", "Review association documents when applicable", "Keep lender and program property rules visible"], affordability: "A sustainable Garland target includes taxes, insurance, utilities, maintenance, and association costs in addition to the mortgage payment.", marketOverview: "Availability and negotiating conditions change. Use current approved property data and property-specific comparable sales rather than unsupported averages.", schoolNote: "Many addresses are served by Garland ISD, but buyers should verify the exact property with the district and Texas Education Agency.", cityUrl: "https://www.garlandtx.gov/", faqs: sharedFaq("Garland") },
  mesquite: { slug: "mesquite", city: "Mesquite", countyContext: "Eastern Dallas County and the DFW region", overview: "Mesquite can appeal to buyers comparing established subdivisions, access to Dallas, property condition, and a practical ownership budget.", searchFocus: "Focus the search by home age, repair tolerance, daily routes, taxes, insurance, and monthly-cost limits.", neighborhoods: ["Creek Crossing", "Town East", "Lawson", "Downtown Mesquite"], housing: ["Established brick homes", "Ranch-style homes", "Two-story suburban homes", "Newer subdivision homes"], buyingTips: ["Budget for inspection findings in older homes", "Verify flood and drainage information", "Compare taxes and insurance by exact address", "Review nearby road and development plans through official sources"], affordability: "List price is only the first comparison. Older systems, insurance, taxes, utilities, and maintenance reserves can materially affect the ownership plan.", marketOverview: "Current supply and competition should be evaluated at the price band and property-type level using approved live data at the time of the search.", schoolNote: "Many addresses are associated with Mesquite ISD; verify the exact attendance zone and any district boundary before relying on it.", cityUrl: "https://www.cityofmesquite.com/", faqs: sharedFaq("Mesquite") },
  richardson: { slug: "richardson", city: "Richardson", countyContext: "Dallas and Collin counties within the DFW region", overview: "Richardson includes established neighborhoods, varied property ages, and addresses spanning two counties, making address-level cost and school verification important.", searchFocus: "Compare property condition, county and tax details, travel needs, lot and home type, and documented ownership costs.", neighborhoods: ["Canyon Creek", "Heights Park", "Greenwood Hills", "Duck Creek"], housing: ["Mid-century homes", "Established brick homes", "Townhomes", "Updated and infill properties"], buyingTips: ["Confirm county and taxing entities", "Inspect older systems and prior improvements", "Verify school boundaries by address", "Compare association and maintenance obligations"], affordability: "Two similarly priced Richardson homes can differ in taxes, insurance, condition, and expected maintenance. Build the budget from the exact property.", marketOverview: "Neighborhood-level activity can differ from citywide headlines. Review current listings, recent comparable sales, condition, and days-on-market evidence before setting terms.", schoolNote: "Addresses may fall within Richardson ISD, Plano ISD, or another applicable boundary. Confirm directly for the property.", cityUrl: "https://www.cor.net/", faqs: sharedFaq("Richardson") },
  plano: { slug: "plano", city: "Plano", countyContext: "Collin and Denton counties within the DFW region", overview: "Plano provides a broad mix of established homes, townhomes, and newer development, with significant variation in size, association costs, and ownership expenses.", searchFocus: "Define the maximum complete monthly cost, preferred property type, maintenance capacity, and travel needs before choosing a search area.", neighborhoods: ["Downtown Plano", "Legacy area", "East Plano", "West Plano"], housing: ["Established suburban homes", "Townhomes and condominiums", "Larger two-story homes", "Newer mixed-use-area housing"], buyingTips: ["Review HOA rules and financial documents", "Check property age and major system updates", "Verify taxes and special assessments", "Separate square-footage wants from sustainable cost"], affordability: "A higher purchase price is not the only affordability pressure. Association dues, insurance, taxes, utilities, and upkeep for larger homes must be included.", marketOverview: "Competition varies by price, condition, location, and property type. Use current comparable evidence and avoid assuming one citywide trend applies to every home.", schoolNote: "Many addresses are served by Plano ISD, while district boundaries do not always match city boundaries. Verify the exact address.", cityUrl: "https://www.plano.gov/", faqs: sharedFaq("Plano") },
  sachse: { slug: "sachse", city: "Sachse", countyContext: "Dallas and Collin counties in the northeastern DFW region", overview: "Sachse includes established areas and newer master-planned development, requiring buyers to compare taxes, association obligations, commute needs, and construction age.", searchFocus: "Compare established-home maintenance with newer-home taxes, association rules, and possible district assessments using exact property documents.", neighborhoods: ["Woodbridge", "Hudson Crossing", "Sachse Ranch Estates", "Old Town Sachse"], housing: ["Newer suburban homes", "Established single-family homes", "Master-planned communities", "Homes on varied lot sizes"], buyingTips: ["Verify county and school district", "Review HOA and assessment documents", "Inspect drainage and foundation conditions", "Confirm the full tax estimate for new construction"], affordability: "Newer construction may reduce some near-term repairs but can carry different taxes, association dues, landscaping, and upgrade costs. Compare the complete picture.", marketOverview: "Sachse inventory can be sensitive to subdivision, build age, and price range. Use live approved data and exact property disclosures.", schoolNote: "Addresses may be served by Garland ISD or Wylie ISD. Confirm the property directly with the relevant district.", cityUrl: "https://www.cityofsachse.com/", faqs: sharedFaq("Sachse") },
  rowlett: { slug: "rowlett", city: "Rowlett", countyContext: "Dallas and Rockwall counties near Lake Ray Hubbard", overview: "Rowlett buyers may compare established neighborhoods, newer construction, lake-adjacent considerations, transportation, and addresses in two counties.", searchFocus: "Verify flood and insurance considerations, county, taxes, association documents, property condition, and daily travel needs for each address.", neighborhoods: ["Waterview", "Dalrock", "Lakewood Pointe", "Downtown Rowlett"], housing: ["Established brick homes", "Lake-adjacent homes", "Newer subdivision homes", "Townhome options"], buyingTips: ["Review official flood information", "Quote insurance before the option period ends", "Verify county and school boundaries", "Inspect drainage, roof, foundation, and exterior systems"], affordability: "Insurance, flood considerations, taxes, association dues, and maintenance can change the real cost of a Rowlett property beyond principal and interest.", marketOverview: "Lake proximity, condition, subdivision, and county can affect property comparisons. Use current MLS and property-specific evidence.", schoolNote: "Addresses may be served by Garland ISD or Rockwall ISD. Verify boundaries for the exact property.", cityUrl: "https://www.rowletttx.gov/", faqs: sharedFaq("Rowlett") },
  forney: { slug: "forney", city: "Forney", countyContext: "Kaufman County and the eastern DFW region", overview: "Forney includes substantial newer development alongside established areas, giving buyers important choices around taxes, commute, construction stage, and community obligations.", searchFocus: "Compare new and resale homes using total taxes, possible district assessments, warranties, inspections, upgrades, commute, and future development information.", neighborhoods: ["Devonshire", "Travis Ranch", "Windmill Farms", "Downtown Forney"], housing: ["New construction", "Recent resale homes", "Master-planned communities", "Established homes near the city core"], buyingTips: ["Confirm taxes and district assessments", "Use an independent inspection for new construction", "Review builder warranties and HOA documents", "Test travel routes and research official road plans"], affordability: "Builder incentives can change upfront numbers but do not replace a long-term comparison of taxes, insurance, assessments, utilities, maintenance, and loan terms.", marketOverview: "New-build releases, resale inventory, incentives, and construction timelines change frequently. Compare written terms and current property-level data.", schoolNote: "Many addresses are served by Forney ISD, but buyers should confirm the exact district and campus boundary.", cityUrl: "https://www.forneytx.gov/", faqs: sharedFaq("Forney") },
  rockwall: { slug: "rockwall", city: "Rockwall", countyContext: "Rockwall County near Lake Ray Hubbard", overview: "Rockwall combines established neighborhoods, newer communities, and lake-related property considerations within a smaller county east of Dallas.", searchFocus: "Balance payment, property condition, lake or drainage considerations, association rules, taxes, and realistic travel requirements.", neighborhoods: ["The Shores", "Chandlers Landing", "Stone Creek", "Downtown Rockwall"], housing: ["Established suburban homes", "Lake-adjacent properties", "Newer community homes", "Townhomes and varied-lot properties"], buyingTips: ["Review flood, drainage, and insurance information", "Understand marina or HOA obligations when applicable", "Inspect retaining, foundation, roof, and exterior systems", "Verify county records and tax estimates"], affordability: "Property features and association obligations can affect costs significantly. Build the budget around the exact home, not a broad Rockwall estimate.", marketOverview: "Water proximity, lot, condition, community rules, and price band can produce different negotiating conditions. Use current approved data.", schoolNote: "Many addresses are served by Rockwall ISD; confirm the exact district and attendance boundary before making a decision.", cityUrl: "https://www.rockwall.com/", faqs: sharedFaq("Rockwall") },
  wylie: { slug: "wylie", city: "Wylie", countyContext: "Collin, Dallas, and Rockwall counties in northeastern DFW", overview: "Wylie spans three counties and includes established neighborhoods and newer development, so exact-address verification matters for taxes, schools, and services.", searchFocus: "Compare county, school district, taxes, association dues, home age, condition, travel needs, and planned development using official sources.", neighborhoods: ["Woodbridge", "Birmingham Farms", "Bozman Farms", "Downtown Wylie"], housing: ["Established single-family homes", "Newer subdivision homes", "Master-planned communities", "Homes with varied lots and ages"], buyingTips: ["Confirm the county and all taxing entities", "Verify school boundaries by address", "Review HOA and assessment documents", "Inspect drainage, foundation, roof, and major systems"], affordability: "County, taxes, assessments, insurance, association dues, and maintenance can vary across Wylie addresses. Compare exact written figures.", marketOverview: "Housing age, subdivision, county, condition, and price range influence current inventory and negotiation. Use current MLS evidence when available.", schoolNote: "Many addresses are served by Wylie ISD, while portions may involve other districts. Verify the exact property.", cityUrl: "https://www.wylietexas.gov/", faqs: sharedFaq("Wylie") },
}

export const AREA_LIST = Object.values(AREAS)
