export type BuyerResourceSlug = "first-time-home-buyers" | "credit-improvement" | "down-payment-assistance" | "homeownership-readiness" | "closing-process" | "faq"

export type BuyerResource = {
  slug: BuyerResourceSlug
  title: string
  eyebrow: string
  summary: string
  directAnswer: string
  steps: Array<{ title: string; description: string }>
  questions: Array<{ question: string; answer: string }>
  officialResources: Array<{ label: string; href: string }>
}

export const BUYER_RESOURCES: Record<BuyerResourceSlug, BuyerResource> = {
  "first-time-home-buyers": {
    slug: "first-time-home-buyers", title: "First-Time Homebuyer Guide for North Texas", eyebrow: "Start with the process", summary: "A plain-language path from early preparation through financing, home search, contract, due diligence, closing, and the first months of ownership.", directAnswer: "A first-time buyer should begin by building a sustainable budget, reviewing credit and savings, speaking with qualified lenders or approved programs, and learning the transaction before touring homes.",
    steps: [{ title: "Organize the starting numbers", description: "List income, recurring debts, available savings, expected moving costs, and a monthly housing range that leaves room for real life." }, { title: "Compare financing", description: "Request written estimates from qualified lenders using the same assumptions; compare payment, cash-to-close, mortgage insurance, and long-term cost." }, { title: "Define the search", description: "Rank needs, neutral location criteria, condition tolerance, and ownership responsibilities before touring." }, { title: "Protect the transaction", description: "Understand the contract, option period, inspection, appraisal, title, insurance, lender conditions, walkthrough, and closing figures." }],
    questions: [{ question: "What is the first step to buying a home?", answer: "The most useful first step is usually a readiness and budget conversation—not browsing listings. Organize your numbers and questions before choosing a financing or search path." }, { question: "Do I need 20 percent down?", answer: "Not always. Some verified programs permit lower down payments, but the full cost and eligibility must be confirmed by a qualified lender or program." }, { question: "How long does buying a home take?", answer: "There is no guaranteed timeline. Preparation, financing, inventory, contract terms, inspections, appraisal, title, and underwriting all affect timing." }, { question: "Should I use the maximum preapproval amount?", answer: "A preapproval is not a spending recommendation. Choose a complete monthly cost that protects savings, maintenance capacity, and other goals." }],
    officialResources: [{ label: "HUD homebuying resources", href: "https://www.hud.gov/buying" }, { label: "Texas Real Estate Commission consumer information", href: "https://www.trec.texas.gov/public" }],
  },
  "credit-improvement": {
    slug: "credit-improvement", title: "Credit Improvement Before Homebuying", eyebrow: "Prepare without shame", summary: "Understand the credit information lenders may review, correct verified errors, protect payment history, and build a documented plan without promises of a score increase or loan approval.", directAnswer: "Start by reviewing reports from the federally authorized source, disputing verified errors through the proper channels, paying obligations on time, and avoiding major credit changes without discussing the impact with a qualified lender or counselor.",
    steps: [{ title: "Pull official reports", description: "Use AnnualCreditReport.com, review all listed accounts and identifying information, and save documentation of any confirmed error." }, { title: "Dispute accurately", description: "Dispute information only when it is incomplete or inaccurate; keep copies and track responses." }, { title: "Protect consistency", description: "Pay on time, keep balances and new applications under control, and avoid closing accounts solely to chase a score." }, { title: "Get qualified guidance", description: "A HUD-approved housing counselor or qualified lender can explain how verified credit information affects the next step." }],
    questions: [{ question: "Can a real-estate agent repair my credit?", answer: "No. Debra can help you organize homebuying questions, but credit reporting, disputes, counseling, and lending decisions belong with the appropriate organizations and professionals." }, { question: "How fast can a score improve?", answer: "There is no reliable universal timeline or guaranteed increase. The cause, accuracy of the report, creditor reporting cycles, and individual credit file all matter." }, { question: "Should I pay every collection before applying?", answer: "Do not rely on a universal answer. Ask a qualified lender or counselor to explain how a verified account and proposed action may affect the specific financing plan." }, { question: "Where can I get my credit reports?", answer: "AnnualCreditReport.com is the federally authorized source for free credit reports. Avoid websites that imitate the official service." }],
    officialResources: [{ label: "Official Annual Credit Report", href: "https://www.annualcreditreport.com/" }, { label: "Consumer Financial Protection Bureau credit guidance", href: "https://www.consumerfinance.gov/consumer-tools/credit-reports-and-scores/" }],
  },
  "down-payment-assistance": {
    slug: "down-payment-assistance", title: "Down Payment Assistance in Dallas–Fort Worth", eyebrow: "Verify before relying", summary: "Learn how assistance programs may interact with the first mortgage, income and location rules, repayment or forgiveness terms, approved lenders, property requirements, and closing timelines.", directAnswer: "Down payment assistance is not one universal grant. Programs differ by funding, location, household rules, approved lender, property, education, repayment terms, and availability, so every detail must be verified before making an offer.",
    steps: [{ title: "Identify official programs", description: "Start with government, housing-finance-agency, city, county, or HUD-approved counseling sources rather than an advertisement alone." }, { title: "Read the obligation", description: "Ask whether assistance is a grant, forgivable loan, deferred loan, repayable loan, or other structure and what triggers repayment." }, { title: "Confirm lender and property rules", description: "Verify approved lenders, first-mortgage pairing, income, price, location, occupancy, property, and education requirements." }, { title: "Protect the closing plan", description: "Confirm reservation, funding availability, processing time, required documents, and final cash-to-close before relying on assistance." }],
    questions: [{ question: "Is down payment assistance free money?", answer: "Not always. Some assistance is repayable, deferred, forgivable over time, or subject to occupancy and resale rules. Read the official terms." }, { question: "Can assistance cover closing costs?", answer: "Some programs may permit certain closing costs while others do not. The program administrator and lender must confirm permitted uses." }, { question: "Can assistance run out?", answer: "Funding and reservation availability can change. Do not rely on an amount until the approved parties confirm it for the transaction." }, { question: "Does assistance guarantee mortgage approval?", answer: "No. The first mortgage and assistance program each have requirements, and neither should be treated as guaranteed." }],
    officialResources: [{ label: "Texas State Affordable Housing Corporation", href: "https://www.tsahc.org/homebuyers-renters" }, { label: "Texas Department of Housing and Community Affairs", href: "https://www.tdhca.texas.gov/homebuyers" }, { label: "HUD-approved housing counselors", href: "https://www.hud.gov/counseling" }],
  },
  "homeownership-readiness": {
    slug: "homeownership-readiness", title: "Homeownership Readiness Checklist", eyebrow: "Plan before pressure", summary: "Use five readiness areas—monthly budget, savings, credit, documentation, and ownership capacity—to identify the next useful step without grading yourself or claiming qualification.", directAnswer: "Readiness means you understand the complete cost, have a documented financing conversation, can manage expected and unexpected ownership expenses, and are prepared for the time and decisions required by the transaction.",
    steps: [{ title: "Monthly stability", description: "Know the housing payment you can sustain after other debts, savings, transportation, food, healthcare, family, and lifestyle costs." }, { title: "Cash plan", description: "Separate down payment, closing costs, moving, immediate repairs, and emergency reserves." }, { title: "Documentation", description: "Organize identification, income, employment, asset, debt, housing, and program documents requested by the appropriate professional." }, { title: "Ownership capacity", description: "Plan for maintenance, utilities, insurance, taxes, association duties, and time required to care for the property." }],
    questions: [{ question: "How do I know if I am ready to buy?", answer: "Readiness is broader than loan eligibility. It includes sustainable cost, cash reserves, stable documentation, property responsibilities, timing, and a clear reason for buying." }, { question: "Should I wait until my finances are perfect?", answer: "Perfection is not the standard. Accurate information and a realistic plan help identify whether to prepare, compare options, or begin a search." }, { question: "Does paying rent prove mortgage readiness?", answer: "Rent history can be relevant, but ownership adds taxes, insurance, maintenance, transaction costs, and financing requirements." }, { question: "Can I complete readiness planning anonymously?", answer: "Yes. The site’s calculators and education can be used without submitting contact information." }],
    officialResources: [{ label: "HUD-approved housing counselors", href: "https://www.hud.gov/counseling" }, { label: "CFPB owning a home tools", href: "https://www.consumerfinance.gov/owning-a-home/" }],
  },
  "closing-process": {
    slug: "closing-process", title: "Texas Home Closing Process", eyebrow: "From contract to keys", summary: "Understand the typical work between an accepted contract and closing: option period, inspections, financing, appraisal, title, insurance, disclosures, final walkthrough, and signed settlement documents.", directAnswer: "Closing is the completion of coordinated contract, title, financing, insurance, and settlement work. Dates and responsibilities come from the signed contract and qualified professionals, not a guaranteed generic timeline.",
    steps: [{ title: "Open the transaction", description: "Deliver required contract items, confirm title and lender contacts, record deadlines, and understand the option period and earnest-money obligations." }, { title: "Complete due diligence", description: "Use qualified inspectors and specialists, review disclosures and reports, and make repair or termination decisions within the contract." }, { title: "Finish financing and title", description: "Respond to lender conditions, complete the appraisal and insurance process, review title documents, and avoid unapproved financial changes." }, { title: "Review and close", description: "Review the lender’s Closing Disclosure when applicable, verify funds and identification instructions, complete the walkthrough, sign, and wait for funding confirmation." }],
    questions: [{ question: "Is closing day the same as getting the keys?", answer: "Not always. Possession depends on the contract and completion of signing and funding. Confirm the exact arrangement before making moving plans." }, { question: "What is the option period in Texas?", answer: "It is a negotiated contract period that may provide a termination right under stated terms. The signed contract and qualified guidance control the exact deadline and requirements." }, { question: "Why do I need title work?", answer: "The title process researches ownership and listed interests and supports the closing and title-insurance process. Ask the title company or attorney to explain property-specific questions." }, { question: "Can final cash-to-close change?", answer: "Yes. Lender, title, insurance, taxes, credits, prorations, and other verified figures can change. Use the final official instructions and disclosures." }],
    officialResources: [{ label: "CFPB mortgage closing checklist", href: "https://www.consumerfinance.gov/owning-a-home/close/" }, { label: "Texas Real Estate Commission consumer information", href: "https://www.trec.texas.gov/public" }],
  },
  faq: {
    slug: "faq", title: "North Texas Homebuyer Frequently Asked Questions", eyebrow: "Clear answers first", summary: "Direct, nonjudgmental answers to common questions about starting, credit, financing, assistance, agents, inspections, affordability, and closing.", directAnswer: "You do not need every answer before starting. You need accurate information about where you are, one useful next step, and the right licensed or approved professional for each decision.",
    steps: [{ title: "Start with the concern", description: "Name the question that is stopping you instead of trying to learn the entire process at once." }, { title: "Find the right source", description: "Use official program sources for program rules, lenders for financing, inspectors for condition, and qualified legal or tax professionals for their fields." }, { title: "Document the answer", description: "Keep written estimates, dates, disclosures, program rules, and follow-up questions together." }, { title: "Choose one next step", description: "Move from general research to one practical action: request reports, meet a counselor, compare lenders, or plan a consultation." }],
    questions: [{ question: "Can I buy a home with less-than-perfect credit?", answer: "Possibly, but no website or agent can determine that from a score alone. Review accurate reports and speak with a qualified lender or HUD-approved counselor about verified options." }, { question: "How much home can I afford?", answer: "Use a complete budget, not only a lender maximum. Include taxes, insurance, mortgage insurance, association dues, utilities, maintenance, reserves, and other goals." }, { question: "Do I need a real-estate agent before getting preapproved?", answer: "You may begin education and planning with an agent before preapproval. A verified lender or program conversation is normally needed before relying on a price range or writing an offer." }, { question: "What is the difference between appraisal and inspection?", answer: "An appraisal primarily supports valuation and lender requirements. An independent inspection evaluates condition for the buyer; neither replaces the other." }, { question: "Are online estimates exact?", answer: "No. Calculators and automated values use assumptions. Use current lender, tax, insurance, title, inspection, and property information for decisions." }, { question: "Can Debra guarantee approval or assistance?", answer: "No. Debra provides education and real-estate representation. Lenders and official programs control eligibility, terms, funding, and approval." }],
    officialResources: [{ label: "Consumer Financial Protection Bureau homebuyer tools", href: "https://www.consumerfinance.gov/owning-a-home/" }, { label: "HUD housing counseling", href: "https://www.hud.gov/counseling" }],
  },
}

export const BUYER_RESOURCE_LIST = Object.values(BUYER_RESOURCES)
