/**
 * Minimal, deterministic authoring DSL used by the article migration.
 *
 * The DSL exists so migrated copy is stored once, as structured content, and
 * can be regenerated byte-for-byte. It supports the inline marks the migrated
 * articles actually use: bold (`**text**`) and links (`[label](/href)`).
 *
 * Keys are generated from a per-document counter so repeated runs of
 * `scripts/content/build-articles.mjs` produce identical output.
 */

export function createKeyFactory(prefix) {
  let counter = 0
  return () => `${prefix}${(counter += 1).toString(36)}`
}

const INLINE_PATTERN = /(\*\*[^*]+\*\*)|(\[[^\]]+\]\([^)]+\))/g

function parseInline(text, key) {
  const children = []
  const markDefs = []
  let lastIndex = 0
  let match

  const push = (value, marks) => {
    if (!value) return
    children.push({ _type: "span", _key: key(), text: value, marks: marks ?? [] })
  }

  INLINE_PATTERN.lastIndex = 0
  while ((match = INLINE_PATTERN.exec(text)) !== null) {
    push(text.slice(lastIndex, match.index))
    if (match[1]) {
      push(match[1].slice(2, -2), ["strong"])
    } else {
      const link = /\[([^\]]+)\]\(([^)]+)\)/.exec(match[2])
      const markKey = key()
      markDefs.push({ _type: "link", _key: markKey, href: link[2] })
      push(link[1], [markKey])
    }
    lastIndex = INLINE_PATTERN.lastIndex
  }
  push(text.slice(lastIndex))

  return { children, markDefs }
}

function block(text, key, { style = "normal", listItem, level } = {}) {
  const { children, markDefs } = parseInline(text, key)
  const result = { _type: "block", _key: key(), style, children, markDefs }
  if (listItem) {
    result.listItem = listItem
    result.level = level ?? 1
  }
  return result
}

/** Builds the prose helpers bound to one document's key factory. */
export function createProse(key) {
  return {
    p: (text) => block(text, key),
    h2: (text) => block(text, key, { style: "h2" }),
    h3: (text) => block(text, key, { style: "h3" }),
    h4: (text) => block(text, key, { style: "h4" }),
    ul: (items) => items.map((item) => block(item, key, { listItem: "bullet" })),
    ol: (items) => items.map((item) => block(item, key, { listItem: "number" })),
  }
}

/** Flattens nested prose arrays into a single Portable Text array. */
export function pt(...parts) {
  return parts.flat(Infinity).filter(Boolean)
}
