import Image from "next/image"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Container } from "@/components/ui/container"

export function ControlledHomeSections() {
  return <>
    <section className="editorial-section" aria-labelledby="who-heading"><Container className="intro-grid"><div><p className="eyebrow">A real person. A practical plan.</p><h2 id="who-heading">Homeownership has steps. You don’t have to learn them alone.</h2></div><div className="section-copy"><p>D’Affordable Homes is led by Debra Allen, REALTOR®. She helps first-time buyers and families slow the process down, understand the decisions in front of them, and move forward when the plan is ready.</p><Link className="text-link" href="/about">Get to know Debra →</Link></div></Container></section>
    <section className="editorial-section soft-band" aria-labelledby="path-heading"><Container><div className="section-heading-row"><div><p className="eyebrow">Choose your path</p><h2 id="path-heading">Start where you are.</h2></div><p className="section-intro">Whether you are preparing to buy or looking for your next clear step, the conversation begins with what matters to you.</p></div><div className="pathway-row"><Link href="/first-time-buyers" className="pathway-panel"><span className="pathway-kicker">For buyers</span><h3>Prepare to buy with confidence.</h3><p>Understand the process, explore affordability, and build a plan before you search.</p><span className="text-link">Explore buyer guidance →</span></Link><Link href="/contact" className="pathway-panel"><span className="pathway-kicker">For homeowners and sellers</span><h3>Talk through your next move.</h3><p>Bring your questions to Debra and clarify what support is available for your situation.</p><span className="text-link">Start a conversation →</span></Link></div></Container></section>
    <section className="editorial-section" aria-labelledby="local-heading"><Container className="feature-grid"><div className="feature-image"><Image src="/images/black-family-home-pexels-7114188.webp" alt="A family together in a bright home" fill sizes="(min-width: 1024px) 48vw, 100vw" className="object-cover" /></div><div className="section-copy"><p className="eyebrow">Garland + DFW</p><h2 id="local-heading">Local guidance should feel like local knowledge.</h2><p>From Garland to the wider Dallas–Fort Worth area, the right home decision depends on more than a listing. Debra helps you ask better questions about neighborhoods, timing, preparation, and the life you want to build.</p><Link className="text-link" href="/areas">Explore the areas →</Link></div></Container></section>
    <section className="editorial-section process-section" aria-labelledby="process-heading"><Container><div className="section-heading-row"><div><p className="eyebrow">How Debra works</p><h2 id="process-heading">Clear guidance, one decision at a time.</h2></div><p className="section-intro">You do not need every answer today. You need a next step you can actually follow.</p></div><ol className="process-list"><li><span>01</span><div><h3>Listen</h3><p>Start with your goals, questions, timeline, and current starting point.</p></div></li><li><span>02</span><div><h3>Plan</h3><p>Make the numbers, preparation, and options easier to understand.</p></div></li><li><span>03</span><div><h3>Explore</h3><p>Evaluate homes, neighborhoods, and tradeoffs with context.</p></div></li><li><span>04</span><div><h3>Move forward</h3><p>Take the next step when it is informed and right for you.</p></div></li></ol></Container></section>
    <section className="editorial-section soft-band" aria-labelledby="program-heading"><Container className="program-feature"><div><p className="eyebrow">Homebuyer programs + affordability guidance</p><h2 id="program-heading">Understand the path before you choose it.</h2><p className="section-copy">Explore NACA, Homes for Heroes, calculators, and practical resources with official information and clear boundaries.</p></div><div className="open-link-list"><Link href="/programs/naca"><span>NACA homebuyer help</span><b>→</b></Link><Link href="/programs/homes-for-heroes"><span>Homes for Heroes guidance</span><b>→</b></Link><Link href="/calculators"><span>Planning calculators</span><b>→</b></Link></div></Container></section>
    <section className="editorial-section" aria-labelledby="resources-heading"><Container className="resources-layout"><div><p className="eyebrow">Practical resources</p><h2 id="resources-heading">Useful information for the decision in front of you.</h2></div><div className="open-link-list"><Link href="/calculators"><span>Plan with real numbers</span><b>→</b></Link><Link href="/blog/how-to-buy-home-garland-tx"><span>How to buy a home in Garland</span><b>→</b></Link><Link href="/resources"><span>Browse the resource library</span><b>→</b></Link></div></Container></section>
    <section className="consultation-band" aria-labelledby="consultation-heading"><Container className="consultation-inner"><div><p className="eyebrow">Your next step</p><h2 id="consultation-heading">You do not need every answer before you talk with Debra.</h2><p>Bring your questions, your goals, or simply your starting point.</p></div><Button href="/consultation" size="lg">Book a consultation</Button></Container></section>
  </>
}
